integrationArchitecture/Models/Cat.cs
namespace integrationArchitecture.Models
{
    //
    public class Cat
    {
        public string fact { get; set; }
        public int length { get; set; }
    }
}

integrationArchitecture/Models/Directors.cs
namespace integrationArchitecture.Models
{
    //
    public class Directors
    {
        public string Director { get; set; }
        public string Movie { get; set; }

    }
}

integrationArchitecture/Models/ErrorViewModel.cs
namespace integrationArchitecture.Models
{
    //
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

integrationArchitecture/Controllers/CatsController.cs
using integrationArchitecture.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
//
namespace integrationArchitecture.Controllers
{
    public class CatsController : Controller
    {
        // GET: CatsController
      HttpClient client = new HttpClient();

        public async Task<IActionResult> Index()
        {
            string url = "https://catfact.ninja/fact";
            var response = await client.GetStringAsync(url);
            var cats = JsonConvert.DeserializeObject<Cat>(response);

            return View(cats);
        }


        // GET: CatsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CatsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CatsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CatsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CatsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CatsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CatsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

integrationArchitecture/Controllers/DirectorsController.cs
using integrationArchitecture.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
//
namespace integrationArchitecture.Controllers
{
    public class DirectorsController : Controller
    {
        // GET: DirectorsController
        public async Task<ActionResult> Index()
        {
            string apiUrl = "https://localhost:7220/api/director";

            List<Directors> directors = new List<Directors>();

            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(apiUrl);

                var result = await response.Content.ReadAsStringAsync();
                directors = JsonConvert.DeserializeObject<List<Directors>>(result);
            }

            return View(directors);
        }

        // GET: DirectorsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DirectorsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DirectorsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Directors directors)
        {
            string apiUrl = "https://localhost:7220/api/director";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(directors), Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PostAsync(apiUrl, content);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(directors);
        }

        // GET: DirectorsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DirectorsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DirectorsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DirectorsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

integrationArchitecture/Controllers/HomeController.cs
using integrationArchitecture.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
//
namespace integrationArchitecture.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

integrationArchitecture/Views/Cats/Index.cshtml
@model Cat
@{ ViewData ["Title"] = "About Cats"; }

<h1> @ViewData["Title"]</h1>

<div>
	<h3>Facts about Cats :) </h3>
	<p>@Model.fact </p>
	<p>@Model.length characters</p>

	

</div>

integrationArchitecture/Views/Directors/Create.cshtml
@model integrationArchitecture.Models.Directors

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Directors</h4>
<hr />
<br />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Movie" class="control-label"></label>
                <input asp-for="Movie" class="form-control" />
                <span asp-validation-for="Movie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

integrationArchitecture/Views/Directors/Details.cshtml
@model integrationArchitecture.Models.Directors

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Directors</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Director)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

integrationArchitecture/Views/Directors/Index.cshtml
@model IEnumerable<integrationArchitecture.Models.Directors>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

integrationArchitecture/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

integrationArchitecture/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - integrationArchitecture</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/integrationArchitecture.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">integrationArchitecture</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Directors" asp-action="Index">Director Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cats" asp-action="Index">About Cats</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - integrationArchitecture - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>